---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey
resources:
  - ../../../base/valkey
configMapGenerator:
  - name: valkey-values
    namespace: valkey
    files:
      - values.yaml
secretGenerator:
  - name: valkey-secrets-values
    namespace: valkey
    files:
      - secrets.values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
patches:
  - target:
      kind: HelmRelease
      name: valkey
    path: patches/helmrelease.yaml
