auth:
    aclUsers:
        admin:
            permissions: ENC[AES256_GCM,data:GbUZJzowHsbyDqU=,iv:iqN8bYj6vlZcfqCZjxDmDHyobjVLifm3fPyIHeFaclw=,tag:2/JpNCJNL/4i0TNVaMiGjw==,type:str]
            password: ENC[AES256_GCM,data:NUogmgcN+p6nyuPoixL8UY1EJTLe,iv:aN9kxYnLS2F125TRlizNk36i/VLOaDACVKnMGkRSS7o=,tag:5zAay2slpvZi99URPMfjEA==,type:str]
        default:
            permissions: ENC[AES256_GCM,data:F3qc1GG8Zx5vHEymhZdBPuJjPxIY3cDTHg==,iv:LXisDlYliDJU+N65xCiNLmewSxcoP61iBFs6qD73uIE=,tag:inwnMM/daHYwkO8Pyl5ESA==,type:str]
            password: ENC[AES256_GCM,data:/lJgRZjOPac9sLZMofwD8nLG0jdiVA4=,iv:Vsvehmgmv1GfaMpKpDgGm0eLi+/tROc9Djt5tBWr96g=,tag:ejTl1O9XuaM6E/A4xRZvBg==,type:str]
        gateway:
            permissions: ENC[AES256_GCM,data:bsBsCxqjZovcUdiYA4slOmgfD0crLjFvRE+k0JfRB5EY,iv:Xqoy+nxqRF1XjQSRJjKOHDwBxNLyzfXpXH3FLio7nPs=,tag:7d6L6HAzEF8W26HvHF2Uag==,type:str]
            password: ENC[AES256_GCM,data:a+X1uV6BknrlTIqz4N249do8qlCVMUw=,iv:0gZ6Nan0dsAwbuegx2YxgpP6mZ16JaH7YhLgKT78xjM=,tag:0l9fAws+ncQWFnbYcYUp3w==,type:str]
        replication:
            permissions: ENC[AES256_GCM,data:LjiEDkay9Bx6n4KdeNRCYTs89wLQ2w==,iv:cqzoFjGKH/1xmpS1RtxyFhuuKZ1oujRPqzerbogWZSg=,tag:Oig/oYG2xacLGxDEw3JsqA==,type:str]
            password: ENC[AES256_GCM,data:zBXs0syfXNkgNMUVEAMiOepNBCgnphxxKBwr,iv:fX8f9YR64Ml2ZlxVFUQyAud5poWu9oKQu2wOSQuaMTc=,tag:fZjpcpdO/7Wn+n6eU2/eaQ==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOEJyZWVFK3NUU1I3NEk2
            OUs5WkN3b2pkR24yUkFMNVhKOU4zZzkzMnkwCmpOc2R5U3JMTlBIdlJIL0VzWWw0
            ZHllQk4yR1FBZXJjMG4rWmVBMVVQUkkKLS0tIE9DaVVETy9wZEtYRDJON3h0dk90
            VTJhODVQT2w5elJlUGljMUtiYy9RTlUKeBR6q2vblrzmtYgZyV3LDUoOWGSnnuEL
            VA+LVknxP81nQc+1/H0vbDPXM9FJrD/grCOj7qpsEIzRYwBg0vxBJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:26:13Z"
    mac: ENC[AES256_GCM,data:00Blcyh+hM39TngjdUf4jtvn5RXzif4GjrLuTYq++3Mp06IwGRSiUyCRuopuGDwg++nUdc+Xx2A+up6mBiDS/mhCmGzOR+vv59KgAGlhrfIOjz63o8o4rPBHU3OAQVeffdePVSK3V0943MMS5UdmEfpbfz7y2XfVghxnKF0CyKg=,iv:GUhl75upRXBVuHInHEQZF1OK8X8scKDObqOMRkKC+XU=,tag:CZc3Hy1Sa1o7xutCuFLEYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
