---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces
  - ./rbac
  - ./local-path-provisioner
  - ./valkey
  - ./cert-manager
  - ./envoy-gateway
  - ./keycloak-infra
  - ./keycloak
  - ./headlamp
  - ./buildkitd
