app:
    secrets:
        env:
            AUTH_SECRET: ENC[AES256_GCM,data:dbRtNOCAZgRXnmpKci/q5e/Qwz2hgKTP3rT+MHAqkBxnxNEnf9iVK8J4nDk=,iv:aCJDL1zqlbPl+x9CEVbUQTldG0RcBszVaJLsiBmmE04=,tag:Eytu7q8Y09LxwSB5qcFijQ==,type:str]
            AUTH_KEYCLOAK_ID: ENC[AES256_GCM,data:NEOeQjEFyUv13E8=,iv:tAp/h9QzmcIwtjwpJGiSggBkzvP65Gsqfs42lYRNDFA=,tag:I+CPKrIUOEs25IcNtjCh8Q==,type:str]
            AUTH_KEYCLOAK_SECRET: ENC[AES256_GCM,data:HvNohUgpXq5rHZBnZlQ9b5GjwcrerfzivAbFdhxRqiA=,iv:MfL7KW0gPfCSLYjDNVuAj9howfRm3qH0S1kD5CrfDXI=,tag:kTaCXsutnB6CGI7AgKKDDw==,type:str]
            AUTH_KEYCLOAK_ISSUER: ENC[AES256_GCM,data:8eV6SGbpbalQy0GSjdUt19YnOkRC2NjgLp8Vtu7WJ3UOUnJjw2o=,iv:A3ku8LZ4Ibm3AO4B4xDwKNvCUdIMxUMPQf9AugEvnqE=,tag:i7Q2BUfwbctiYhWNpyAOTQ==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS0hrWWc2KzFZS0Y4ck1m
            cmlWbUFDVDluWTFFaXVwcUxTQXBkVmpVQkZBCjBJZU84SllxVVJibk5EVks5a1V0
            MWxQazZEb0RzRlRHTjB3TVUzQ3MyRGcKLS0tIHNFVUJsMmFtaWlUQzJHNWZaeDVp
            NG4yM0VqYWhnZStoUXZKQVY2QkpQa28KvZR3SpiDDDMxW+a9/alXqmnUcb4dx3cI
            V4KbbFkyaiA28inIYOGvl2CkV2j8fzLcZjhAbTJ7cs3n37kNQNMkLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:19:02Z"
    mac: ENC[AES256_GCM,data:dLybV//RtgaHrwBFq5UpPXLPNxDT0200Be7Iai4DN3xSqM8c7cbsg31yb0+Bk53CttEAQc2DTuDOw4NxaFlOsHai+yEfs+E2fyJYXAvSVvalVztRUXWIHOYJ82h1cEkR31wncT7Ngg7nRsijMopxakxhS6TyxrqZZjepsvCKH3Q=,iv:3Zex+XTGBgItPKleiuz6GNYtDkpmsfjogndIPMehtoU=,tag:UcfvXwEL7NK19ICyGc1AGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
