---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/flux-operator
patches:
  - target:
      kind: OCIRepository
      name: flux-operator-repo
    path: patches/ocirepository.yaml
