---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - keycloak-imagerepository.yaml
  - keycloak-imagepolicy-release.yaml
  - keycloak-imagepolicy-latest.yaml
  - infrastructure-imageupdateautomation.yaml
