---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/flux-operator
  - secret.yaml
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
patches:
  - target:
      kind: OCIRepository
      name: flux-operator-repo
    path: patches/ocirepository.yaml
