config:
    oidc:
        clientSecret: ENC[AES256_GCM,data:oO0JX0ZyAqZIb4ecW3yIfKGvvrXqMsbInEbPCVhn9IQ=,iv:02e3RwfFK+RTNEp8yZEIHupapyiffmepdqAx4cCKVXo=,tag:0oKzGzjZJaNZB17dIfQkjw==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWJZelQrUGowdlBReGhC
            LzJsNFRJRUdNbGp5Wkp4VjJwbDJjZHE1MlRvCnowRkJFdDU1NHR5a3dxYlNoamdL
            dnViT2JiY3R0b0NaM2lTRmNaR1ZFa00KLS0tIGt2VDVaVzN2eG9QS0YzQm5ZWmVT
            eGpsa2JqUUsrUytmTlZHb3lTSHBKSFUKgkGobqU+C+k55MbvWk+Uxna4gMdZfPnM
            NQZwap3Qt3u4QFlNvOGCZnuWXJiQYz2+aXFj3Q12NRoAdpSL5yYZDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T13:17:37Z"
    mac: ENC[AES256_GCM,data:+lGkdhJa6BD/vQWiY7Ssw+GupvcH9x1ppLnnhu63j8jJKsc3+xWI+va8XvL89t7BASz9GnXmdvJ6HcUjlJuwkqLohoBhDqds+7usbtzwOjPNqOrcGPpeN2i9OvSY0bsfkSWkU0fo1Nef5+TSCvhQ8EB0UIOGliXn9e/Z3OFu2us=,iv:50iQpybmOIXMxNfmIhSVsb6C3gzRwvmXutOMAEngBec=,tag:a1KIOn+Aihf4FHlaP0EOoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
