---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.19.0/cluster-operator-ghcr-io.yml
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
