---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../base/cert-manager
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
patches:
  - target:
      kind: OCIRepository
      name: cert-manager-repo
    path: patches/ocirepository.yaml
