---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
resources:
  - ../../../base/envoy-gateway
  - gateway.yaml
configMapGenerator:
  - name: envoy-gateway-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
patches:
  - target:
      kind: HelmRelease
      name: envoy-gateway
    path: patches/helmrelease.yaml
  - target:
      kind: OCIRepository
      name: envoy-gateway-repo
    path: patches/ocirepository.yaml
