---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-provisioner
resources:
  - ../../../base/local-path-provisioner
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
patches:
  - target:
      kind: OCIRepository
      name: local-path-provisioner-repo
    path: patches/ocirepository.yaml
