---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../../base/keycloak
configMapGenerator:
  - name: keycloak-values
    namespace: keycloak
    files:
      - values.yaml
secretGenerator:
  - name: keycloak-secrets-values
    namespace: keycloak
    files:
      - secrets.values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
patches:
  - target:
      kind: HelmRelease
      name: keycloak
    path: patches/helmrelease.yaml
  - target:
      kind: OCIRepository
      name: keycloak-repo
    path: patches/ocirepository.yaml
