---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: apps-image-update-automation
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: nix-kubernetes-gitops
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore: update image versions

        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }}/{{ $resource.Name }}:
        {{- range $_, $change := $changes }}
          {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{- end }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps
    strategy: Setters
