---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - imageupdateautomation.yaml
  - ./nix/imagerepository.yaml
  - ./nix/imagepolicy-release.yaml
  - ./nix/imagepolicy-latest.yaml
