---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.18.2/messaging-topology-operator-with-certmanager.yaml
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
