---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector
resources:
  - ../../../base/reflector
patches:
  - target:
      kind: OCIRepository
      name: reflector-repo
    path: patches/ocirepository.yaml
